server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nanami-yu/spring-cloud-config.git
          username:
          password:
          search-paths:
            - spring-cloud-config
          default-label: main
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

